services:
  - type: web
    name: lms-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
      - key: SECRET_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
